name: hold_labs
description: "A game about temprature science"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flame: 1.12.0
  flame_audio: 2.1.5
  flame_tiled: 1.18.1
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: 1.1.2
  flutter_launcher_icons: 0.13.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/tiles/
    - assets/audio/

flutter_icons:
  image_path: "branding/HoldLabs-Logo.png"
  windows:
    generate: true
  # web:
  #   generate: true
  #linux: true
  #android: true
  #ios: true
  #macos: true
